# Site settings
title: Rich's Blog
email: race.richard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog for things to remember.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://richrace.github.io" # the base hostname & protocol for your site
twitter_username: richrace
github_username:  richrace

# Build settings
markdown: kramdown
