# Site settings
title: Rambling Richard
email: race.richard@gmail.com
description: "Read the thoughts on Tech from Richard."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://richrace.github.io" # the base hostname & protocol for your site
twitter_username: richrace
github_username:  richrace

# Build settings
markdown: kramdown

autoprefixer:
  browsers:
  - last 2 versions

plugins:
- jekyll-autoprefixer
